

run:
	@echo 'HMAO tur 3, task E'
	g++ tur3_e.cpp -o tur3_e -lstdc++ -std=c++17
	cat tur3_e.dat | ./tur3_e
tur3_f:
	@echo 'HMAO tur 3, task F'
	g++ tur3_f.cpp -o tur3_f -lstdc++ -std=c++17
	cat tur3_f.dat | ./tur3_f

